# Generated by Django 4.0.5 on 2022-11-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postcode', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('emai', models.CharField(max_length=255)),
                ('additionalinfo', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('headerimage', models.ImageField(null=True, upload_to='')),
                ('title_tag', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('post_date', models.DateField(default=0)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
