# Generated by Django 4.2.1 on 2023-08-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_categories_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='company_n',
        ),
    ]
