# Generated by Django 4.2.1 on 2023-08-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_company_name_company_company_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='company',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='company',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='company',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='company',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='service_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='service_7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
