# Generated by Django 4.2.1 on 2023-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_company_image_2_company_image_3_company_image_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
